---
title: "R Practice"
author: "Emma Clark"
date: "9/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/GitHub/Bay-Area-Future")

```

```{r}
library(tidyverse)

health_full <- read_csv("https://chronicdata.cdc.gov/api/views/6vp6-wxuq/rows.csv?accessType=DOWNLOAD")

```

```{r}
health_ca <- filter(health_full, StateAbbr == "CA")
```

```{r}
pge_19_q1_elec <- read_csv("PGE_2019_Q1_ElectricUsageByZip.zip")
```

```{r}
write_csv(health_ca, "health_ca.csv")
saveRDS(health_ca, "health_ca.rds")

health_ca <- readRDS("health_ca.rds")

save(health_ca, pge_19_q1_elec, file = "working_datasets.rda")
load("working_datasets.rda")
```

```{r}
library(tidyverse)

year <- 2019
quarters <- 1:4
type <- "Electric"

pge_19_elec <- NULL

for(quarter in quarters){
  filename <- paste0(
    "pge/PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv")
  
  print(filename)
  
  temp <- read.csv(filename)
  
  pge_19_elec <- rbind(pge_19_elec,temp)
  
  saveRDS(pge_19_elec, "pge_19_elec.rds")
}


```

